import { ArrowRight, BarChart3, Database, FileText, Sparkles } from 'lucide-react'
import { Link } from 'react-router'

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[var(--background)] text-[var(--text-primary)]"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link to="/" className="flex items-center gap-3 text-lg font-semibold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--accent)] text-white"><BarChart3 size={20}/></span>Kargia</Link><Link to="/login" className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-5 py-2.5 text-sm font-medium">Acceso</Link></header>
    <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-2 lg:py-28"><div><span className="rounded-full bg-[var(--accent-soft)] px-3 py-1.5 text-xs font-semibold text-[var(--accent)]">Inteligencia operativa para equipos</span><h1 className="mt-6 text-5xl font-semibold leading-tight tracking-tight sm:text-6xl">Convierte tus datos en decisiones que mueven el negocio.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--text-secondary)]">Kargia reúne clientes, operaciones, documentación y análisis en espacios seguros para cada equipo.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/solicitar-acceso" className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-5 py-3 font-medium text-white">Solicitar acceso<ArrowRight size={17}/></Link><Link to="/login" className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-5 py-3 font-medium">Ya tengo acceso</Link></div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-16 rounded-full bg-[var(--accent)]/15 blur-3xl"/><div className="relative rounded-3xl border border-[var(--border-soft)] bg-[var(--surface)] p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs text-[var(--text-muted)]">Proyecto activo</p><p className="font-semibold">Operación Norte</p></div><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs text-emerald-600">Actualizado</span></div><div className="grid gap-3 sm:grid-cols-3">{[[Database,'Datos unidos'],[Sparkles,'Insights útiles'],[FileText,'Documentos seguros']].map(([Icon,label]) => { const I=Icon as typeof Database; return <div key={label as string} className="rounded-2xl bg-[var(--surface-elevated)] p-4"><I className="text-[var(--accent)]"/><p className="mt-8 text-sm font-medium">{label as string}</p></div>})}</div><div className="mt-4 h-40 rounded-2xl bg-gradient-to-tr from-[var(--accent)]/20 via-[var(--accent)]/5 to-transparent p-5"><div className="flex h-full items-end gap-3">{[32,55,42,78,64,92,76].map((height,index)=><span key={index} style={{height:`${height}%`}} className="flex-1 rounded-t-md bg-[var(--accent)]/70"/>)}</div></div></div></div>
    </section></main>
}
