import { ArrowLeft, Send } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router'
import { supabase } from '../../services/supabaseClient'

export default function RequestAccessPage() {
  const [form,setForm]=useState({firstName:'',lastName:'',email:'',message:''}); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setStatus('');const {data,error}=await supabase.functions.invoke<{message?:string;error?:string}>('request-access',{body:form});setStatus(error?data?.error??'No se pudo enviar la solicitud.':data?.message??'Solicitud enviada.');setBusy(false)}
  return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-[var(--background)] to-[var(--accent-soft)] p-5"><div className="w-full max-w-lg rounded-3xl border border-[var(--border-soft)] bg-[var(--surface)] p-7 shadow-xl"><Link to="/login" className="inline-flex items-center gap-2 text-sm text-[var(--text-secondary)]"><ArrowLeft size={15}/>Volver al acceso</Link><h1 className="mt-6 text-3xl font-semibold">Solicita acceso a Kargia</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Un administrador revisará tus datos y te contactará por correo.</p><form onSubmit={(event)=>void submit(event)} className="mt-7 grid gap-4 sm:grid-cols-2">{[['Nombre','firstName'],['Apellidos','lastName'],['Correo','email']].map(([label,key])=><label key={key} className={`text-sm text-[var(--text-secondary)] ${key==='email'?'sm:col-span-2':''}`}>{label}<input required type={key==='email'?'email':'text'} value={form[key as keyof typeof form]} onChange={(e)=>setForm({...form,[key]:e.target.value})} className="mt-1.5 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-elevated)] px-3 py-2.5 outline-none focus:border-[var(--accent)]"/></label>)}<label className="text-sm text-[var(--text-secondary)] sm:col-span-2">Mensaje o motivo (opcional)<textarea rows={4} value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})} className="mt-1.5 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-elevated)] px-3 py-2.5 outline-none focus:border-[var(--accent)]"/></label>{status&&<p className="sm:col-span-2 rounded-xl bg-[var(--accent-soft)] p-3 text-sm">{status}</p>}<button disabled={busy} className="sm:col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 font-medium text-white disabled:opacity-60"><Send size={16}/>{busy?'Enviando...':'Enviar solicitud'}</button></form></div></main>
}
